### ISSUE TITLE
Login error on dev server

### ISSUE THREAD

**Issue by JJPro** [NUCSSA/nucssa-core#56]
```
Fatal error: Uncaught Error: Call to undefined function nucssa_core\inc\accounts\ldap_connect() in /home/web/wordpress/wp-content/plugins/nucssa-core/lib/inc/accounts/UserDirectory.php:35 Stack trace: #0 /home/web/wordpress/wp-content/plugins/nucssa-core/lib/inc/accounts/UserDirectory.php(26): nucssa_core\inc\accounts\UserDirectory->__construct() #1 /home/web/wordpress/wp-content/plugins/nucssa-core/lib/inc/accounts/Accounts.php(31): nucssa_core\inc\accounts\UserDirectory::singleton() #2 /home/web/wordpress/wp-includes/class-wp-hook.php(288): nucssa_core\inc\accounts\Accounts::login(NULL, 'xxx', 'xxxxx') #3 /home/web/wordpress/wp-includes/plugin.php(206): WP_Hook->apply_filters(NULL, Array) #4 /home/web/wordpress/wp-includes/pluggable.php(539): apply_filters('authenticate', NULL, 'engineers', '5E96d&ZXdaqT') #5 /home/web/wordpress/wp-includes/user.php(95): wp_authenticate('engineers', '5E96d&ZXdaqT') #6 /home/web/wordpress/wp-login.php(1187): wp_signon(Array, true) #7 {main} thrown in /home/web/wordpress/wp-content/plugins/nucssa-core/lib/inc/accounts/UserDirectory.php on line 35
```

**Comment by JJPro** [comment]
`php-ldap` module is not installed. 
Installed and working now.
